WebFinalProyect/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #Home
  root 'home#index'
  get 'esperanos', to: 'home#waitus'
  get "buscar", to: 'home#find'

  #Login
  get 'login', to: 'users#login'
  post 'login', to: 'users#access'

  #Users
  post 'users/logout'
  get 'usuarios', to: 'users#index', as: 'users'
  post 'usuarios', to: 'users#create'
  get 'usuarios/registrar', to: 'users#new'
  get 'usuarios/:user_id/editar', to: 'users#edit'
  get 'usuarios/:user_id', to: 'users#index', as: 'user'
  patch 'usuarios/:user_id', to: 'users#update'
  put 'usuarios/:user_id', to: 'users#update'
  delete 'usuarios/:user_id', to: 'users#destroy'

  #Proyects
  get 'proyectos', to: 'proyects#index', as: 'proyects'
  post 'proyectos', to: 'proyects#create'
  get 'proyectos/registrar', to: 'proyects#new'
  get 'proyectos/:proyect_id/editar', to: 'proyects#edit'
  get 'proyectos/:proyect_id/portada', to: 'proyects#editcoverpage'
  post 'proyectos/:proyect_id/portada', to: 'proyects#createcoverpage'
  get 'proyectos/:proyect_id', to: 'proyects#show', as: 'proyect'
  patch 'proyectos/:proyect_id', to: 'proyects#update'
  put 'proyectos/:proyect_id', to: 'proyects#update'
  delete 'proyectos/:proyect_id', to: 'proyects#destroy'

  #Departments
  get 'proyectos/:proyect_id/departamentos', to: 'departments#index', as: 'departments'
  post 'proyectos/:proyect_id/departamentos', to: 'departments#create'
  get 'proyectos/:proyect_id/departamentos/registrar', to: 'departments#new'
  get 'proyectos/:proyect_id/departamentos/:department_id/editar', to: 'departments#edit'
  get 'proyectos/:proyect_id/departamentos/:department_id', to: 'departments#show', as: 'department'
  patch 'proyectos/:proyect_id/departamentos/:department_id', to: 'departments#update'
  put 'proyectos/:proyect_id/departamentos/:department_id', to: 'departments#update'
  delete 'proyectos/:proyect_id/departmentos/:department_id', to: 'departments#destroy'
  #   Images
  get 'proyectos/:proyect_id/departamentos/:department_id/imagenes', to: 'departments#images', as: 'departmentimages'
  post 'proyectos/:proyect_id/departamentos/:department_id/imagenes', to: 'departments#createimage'
  get 'proyectos/:proyect_id/departamentos/:department_id/imagenes/subir', to: 'departments#newimage'
  get 'proyectos/:proyect_id/departamentos/:department_id/imagenes/:image_id/editar', to: 'departments#editimage'
  get 'proyectos/:proyect_id/departamentos/:department_id/imagenes/:image_id', to: 'departments#showimage', as: 'departmentimage'
  patch 'proyectos/:proyect_id/departamentos/:department_id/imagenes/:image_id', to: 'departments#updateimage'
  put 'proyectos/:proyect_id/departamentos/:department_id/imagenes/:image_id', to: 'departments#updateimage'
  delete 'proyectos/:proyect_id/departamentos/:department_id/imagenes/:image_id', to: 'departments#destroyimage'
  #   Videos
  get 'proyectos/:proyect_id/departamentos/:department_id/videos', to: 'departments#videos', as: 'departmentvideos'
  post 'proyectos/:proyect_id/departamentos/:department_id/videos', to: 'departments#createvideo'
  get 'proyectos/:proyect_id/departamentos/:department_id/videos/subir', to: 'departments#newvideo'
  get 'proyectos/:proyect_id/departamentos/:department_id/videos/:video_id/editar', to: 'departments#editvideo'
  get 'proyectos/:proyect_id/departamentos/:department_id/videos/:video_id', to: 'departments#showvideo', as: 'departmentvideo'
  patch 'proyectos/:proyect_id/departamentos/:department_id/videos/:video_id', to: 'departments#updatevideo'
  put 'proyectos/:proyect_id/departamentos/:department_id/videos/:video_id', to: 'departments#updatevideo'
  delete 'proyectos/:proyect_id/departamentos/:department_id/videos/:video_id', to: 'departments#destroyvideo'

#Quotations
  get 'cotizaciones', to: 'quotations#index'
  get 'cotizaciones/buscar', to: 'quotations#find'
  get 'proyectos/:proyect_id/departamentos/:department_id/cotizar', to: 'quotations#new', as: 'quotations'
  post 'proyectos/:proyect_id/departamentos/:department_id/cotizar', to: 'quotations#create'
  get 'cotizaciones/:quotation_id/citar', to: 'quotations#editappointment'
  get 'cotizaciones/:quotation_id', to: 'quotations#showquotation', as: 'quotation'
  patch 'cotizaciones/:quotation_id', to: 'quotations#updateappointment'
  put 'cotizaciones/:quotation_id', to: 'quotations#updateappointment'
  get 'citas', to: 'quotations#appointments'
  get 'citas/:quotation_id/editar', to: 'quotations#editappointment'

#Proforms
  post 'crearproforma/:quotation_id', to: 'proforms#create'
  get 'proformas/:proform_id', to:'proforms#show'
  get 'proformas', to: 'proforms#index'

#Payments
  get 'pagos', to: 'payments#index'
  get 'proformas/:proform_id/separar', to:'payments#separate'
  get 'proformas/:proform_id/pagar', to:'payments#newupdate'
  post 'pagos', to: 'payments#create', as: 'payments'

#Reports
  get 'reportes', to: 'reports#index'
  get "reportes/buscar", to: 'reports#find'

  get '/*id', to: 'home#index'
end

WebFinalProyect/app/models/department.rb
class Department < ApplicationRecord
    belongs_to :proyect
    has_many :departmentimage, :dependent => :destroy
    has_many :departmentvideo, :dependent => :destroy
    has_many :quotation
    has_one :payment
    
    validates :category, presence: {message: "presence"}, inclusion: {in: 1..6, message: "inclusion"}
    validates :number, presence: {message: "presence"}, uniqueness: {case_sensitive: false, scope: :proyect_id, message: "uniqueness"}
    validates :floor, presence: {message: "presence"}, numericality: {message: "numericality"}
    validates :area_m2, presence: {message: "presence"}, numericality: {message: "numericality"}
    validates :bathrooms, presence: {message: "presence"}, numericality: {message: "numericality"}
    validates :bedrooms, presence: {message: "presence"}, numericality: {message: "numericality"}
end

WebFinalProyect/app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
    before_action :set_department, only: [:show, :edit, :update, :destroy]
    def index
        allow_access([1])
        set_proyect()
        @departments = Department.where(:proyect_id => params[:proyect_id])
    end
    def new
        allow_access([1])
        set_proyect()
        @department=Department.new
    end
    def create
        allow_access([1])
        @department_params = department_params
        @department_params[:state]=true
        @department = Department.new(@department_params)
        if @department.save
            FileUtils.mkdir_p("public/assets/img/proyects/"+params[:proyect_id].to_s+"/departments/"+@department[:id].to_s)
            render json: {:success=>true, :url=>url_for(controller: 'departments', action: 'index')}
        else
            render json: @department.errors.messages
        end
    end
    def show
        @departmentimages = Departmentimage.where(:department_id => params[:department_id])
        @departmentvideos = Departmentvideo.where(:department_id => params[:department_id])
    end
    def edit
        allow_access([1])
        set_proyect()
    end
    def update
        allow_access([1])
        @department_params = department_params
        @department_params[:state]=true
        if @department.update(@department_params)
            render json: {:success=>true}
        else
            print @department.errors.messages
            render json: @department.errors.messages
        end
    end
    def destroy
        allow_access([1])
        @department.destroy
        FileUtils.rm_rf("public/assets/img/proyects/"+params[:proyect_id]+"/departments/"+@department[:id].to_s)
        redirect_to :controller=>'departments',:action=>'index'
    end

    def images
        set_proyect()
        set_department()
        @departmentimages = Departmentimage.where(:department_id => params[:department_id])
    end
    def showimage

    end
    def newimage
        set_proyect()
        set_department()
        @departmentimage = Departmentimage.new
    end
    def createimage
        tmp = image_params[:file].tempfile
        extname = File.extname(image_params[:file].original_filename)
        if extname == ".jpg"
            @departmentimage = Departmentimage.new(image_params.except(:file))
            if @departmentimage.save
                file = File.join("public/assets/img/proyects/"+params[:proyect_id]+"/departments/"+params[:department_id], @departmentimage[:id].to_s+extname)
                FileUtils.cp tmp.path, file
                render json: {:success=>true, :url=>url_for(controller: 'departments', action: 'images')}
            else
                render json: @departmentimage.errors.messages
            end
        else
            render json: {:image=>["extname"], :url=>url_for(controller: 'departments', action: 'newimage')}
        end
    end
    def editimage
        set_proyect()
        set_department()
        @departmentimage = Departmentimage.find(params[:image_id])
    end
    def updateimage
        set_department()
        set_image()
        if image_params[:file]
            tmp = image_params[:file].tempfile
            extname = File.extname(image_params[:file].original_filename)
            if extname == ".jpg"
                if @departmentimage.update(image_params.except(:file))
                    tmp = image_params[:file].tempfile
                    extname = File.extname(image_params[:file].original_filename)
                    file = File.join("public/assets/img/proyects/"+params[:proyect_id].to_s+"/departments/"+params[:department_id], @departmentimage[:id].to_s+extname)
                    FileUtils.cp tmp.path, file
                    render json: {:success=>true, :url=>url_for(controller: 'departments', action: 'images')}
                else
                    render json: @departmentimage.errors.messages
                end
            else
                render json: {:image=>["extname"], :url=>url_for(controller: 'departments', action: 'editimage')}
            end
        else
            if @departmentimage.update(image_params.except(:file))
                render json: {:success=>true, :url=>url_for(controller: 'departments', action: 'images')}
            else
                render json: @departmentimage.errors.messages
            end
        end        
    end
    def destroyimage
        set_image()
        @departmentimage.destroy
        FileUtils.rm_rf("public/assets/img/proyects/"+params[:proyect_id].to_s+"/departments/"+params[:department_id].to_s+"/"+@departmentimage.id.to_s+".jpg")
        redirect_to :controller=>'departments',:action=>'images'
    end
    
    def videos
        set_proyect()
        set_department()
        @departmentvideos = Departmentvideo.where(:department_id => params[:department_id])
    end
    def showvideo

    end
    def newvideo
        set_proyect()
        set_department()
        @departmentvideo = Departmentvideo.new
    end
    def createvideo
        @departmentvideo = Departmentvideo.new(video_params)
        if @departmentvideo.save
            render json: {:success=>true, :url=>url_for(controller: 'departments', action: 'videos')}
        else
            render json: @departmentvideo.errors.messages
        end
    end
    def editvideo
        set_proyect()
        set_department()
        @departmentvideo = Departmentvideo.find(params[:video_id])
    end
    def updatevideo
        set_department()
        set_video()
        if @departmentvideo.update(video_params)
            render json: {:success=>true, :url=>url_for(controller: 'departments', action: 'videos')}
        else
            render json: @departmentvideo.errors.messages
        end
    end
    def destroyvideo
        set_video()
        @departmentvideo.destroy
        redirect_to :controller=>'departments',:action=>'videos'
    end

    def separate

    end
    
    

    private
    def set_department
        @department = Department.find(params[:department_id])
    end
    def set_proyect
        @proyect = Proyect.find(params[:proyect_id])
    end
    def set_image
        @departmentimage = Departmentimage.find(params[:image_id])
    end
    def set_video
        @departmentvideo = Departmentvideo.find(params[:video_id])
    end
    def department_params
        params.require(:department).permit(:category, :number, :floor, :area_m2, :bathrooms, :bedrooms, :description, :proyect_id)
    end
    def image_params
        params.require(:departmentimage).permit(:name, :description, :file, :department_id)
    end
    def video_params
        params.require(:departmentvideo).permit(:name, :youtube_url, :description, :department_id)
    end
end

WebFinalProyect/app/views/departments/_form.html.erb
<div class="login-dark" style="background-image: url(<%= image_url 'backgrounds/form-bg.jpg' %>);">
    <%= form_with(model: @department, html: {style: "background-color: rgba(255,255,255,0.9);" }) do |f| %>
        <h2 class="text-center" style="color: #ffa555;font-size: 26px; margin-bottom:20px;color: rgb(255,120,0);"><%= form_title %><br>Departamento</h2>
        <p class="text-center" style="color: rgb(0,0,0);margin-top: -10px;font-size: 18px;">Proyecto <%= @proyect.name %></p>
        <div class="form-group">
            <%= f.select :category,
                [
                    ["Normal", 1],
                    ["Estudio", 2],
                    ["Loft", 3],
                    ["Duplex", 4],
                    ["Triplex", 5],
                    ["Penthouse", 6]
                ], {
                    :include_blank => "Tipo de Departamento",
                    :selected => @department.category
                },
                { :class => "form-control form-control-sm", :style=>"color: rgb(0,0,0);" }
            %>
            <p id="form_error_category_presence" class="form-text text-danger text-right form-error">Tipo de Departamento obligatorio</p>
        </div>
        <div class="form-group">
            <small class="form-text text-secondary form-title">Número de Habitación</small>
            <%= f.text_field :number, :value=>@department.number, :type=>"text", :class => "form-control", :autocomplete => "off", :style => "color: rgb(0,0,0);" %>
            <p id="form_error_number_presence" class="form-text text-danger text-right form-error">Número de Habitación obligatorio</p>
            <p id="form_error_number_uniqueness" class="form-text text-danger text-right form-error">Número de Habitación ya existe</p>
        </div>
        <div class="form-group">
            <small class="form-text text-secondary form-title">Piso</small>
            <%= f.text_field :floor, :value=>@department.floor, :type=>"number", :class => "form-control", :autocomplete => "off", :style => "color: rgb(0,0,0);" %>
            <p id="form_error_floor_presence" class="form-text text-danger text-right form-error">Piso obligatorio</p>
        </div>
        <div class="form-group">
            <small class="form-text text-secondary form-title">Área en m²</small>
            <%= f.text_field :area_m2, :value=>number_with_precision(@department.area_m2, :precision => 2), :type=>"number", :class => "form-control", :autocomplete => "off", :style => "color: rgb(0,0,0);" %>
            <p id="form_error_area_m2_presence" class="form-text text-danger text-right form-error">Área en m² obligatorio</p>
        </div>
        <div class="form-group">
            <small class="form-text text-secondary form-title">Cantidad de Baños</small>
            <%= f.text_field :bathrooms, :value=>@department.bathrooms, :type=>"number", :class => "form-control", :autocomplete => "off", :style => "color: rgb(0,0,0);" %>
            <p id="form_error_bathrooms_presence" class="form-text text-danger text-right form-error">Cantidad de baños obligatoria</p>
        </div>
        <div class="form-group">
            <small class="form-text text-secondary form-title">Cantidad de Cuartos</small>
            <%= f.text_field :bedrooms, :value=>@department.bedrooms, :type=>"number", :class => "form-control", :autocomplete => "off", :style => "color: rgb(0,0,0);" %>
            <p id="form_error_bedrooms_presence" class="form-text text-danger text-right form-error">Cantidad de Cuartos obligatoria</p>
        </div>
        <div class="form-group">
            <small class="form-text text-secondary form-title">Descripción</small>
            <%= f.text_area :description, :value=>@department.description, :rows=>3, :class => "form-control", :autocomplete => "off", :style => "color: rgb(0,0,0);" %>
        </div>
        <div class="form-group">
            <%= f.text_field :proyect_id, :value=>@proyect.id, :type=>"number", :class => "form-control d-none", :autocomplete => "off", :style => "color: rgb(0,0,0);" %>
        </div>
        <div class="form-group text-center">
            <%= f.submit form_button, :class=> "btn btn-primary", :style=> "background-color: #ffa555;font-weight: normal;background-color: rgb(255,120,0);" %>
        </div>
        <small id="form_success" class="form-text text-success" style="margin-top:-18px; position: absolute; opacity: 0;"><%= form_success %></small>
    <% end %>
</div>

WebFinalProyect/app/views/departments/_formimage.html.erb
<div class="login-dark" style="background-image: url(<%= image_url 'backgrounds/form-bg.jpg' %>);">
    <%= form_with(model: @departmentimage, url: form_url, html: {style: "background-color: rgba(255,255,255,0.9); max-width:400px;" }) do |f| %>
        <h2 class="text-center" style="color: #ffa555;font-size: 26px; margin-bottom:20px;color: rgb(255,120,0);"><%= form_title%> Imagen</h2>
        <p class="form-control text-center" style="color: rgb(0,0,0); border-bottom: none; margin-top:-15px; font-size:20px;">Proyecto <%= @proyect.name %></p>
        <p class="form-control text-center" style="color: rgb(0,0,0); border-bottom: none; margin-top:-15px;font-size:15px;">Departamento <%= @department.number %></p>
        <div class="form-group">
            <label class="btn btn-outline-secondary" for="fileinput" style="font-family: Montserrat, sans-serif;font-weight: normal;margin-bottom: -10px;margin-right: 0;margin-left: 0; cursor:pointer;">Seleccionar Imagen...</label>
        </div>
        <div class="form-group">
            <% if @departmentimage.id %>
                <img id="preview_image" src=<%= "/assets/img/proyects/"+@proyect[:id].to_s+"/departments/"+@department[:id].to_s+"/"+@departmentimage[:id].to_s+".jpg" %> width="100%" />
            <% else %>
                <img id="preview_image" src=<%= image_url 'no_image.jpg' %> width="100%" />
            <% end %>
            <p id="form_error_image_extname" class="form-text text-danger text-right form-error">Subir imagen .jpg</p>
        </div>
        <div class="form-group">
            <small class="form-text text-secondary form-title">Nombre</small>
            <%= f.text_field :name, :value=>@departmentimage.name, :type=>"text", :class => "form-control", :autocomplete => "off", :style => "color: rgb(0,0,0);" %>
            <p id="form_error_name_presence" class="form-text text-danger text-right form-error">Nombre obligatorio</p>
            <p id="form_error_name_uniqueness" class="form-text text-danger text-right form-error">Nombre ya existe</p>
        </div>
        <div class="form-group">
            <small class="form-text text-secondary form-title">Descripción</small>
            <%= f.text_area :description, :value=>@departmentimage.description, :rows=>3, :class => "form-control", :autocomplete => "off", :style => "color: rgb(0,0,0);" %>
        </div>
        <div class="form-group d-none">
            <%= f.file_field :file, :id=>"fileinput", :accept=>".jpg", :onchange=>"readImage(this);" %>
        </div>
        <div class="form-group">
            <%= f.text_field :department_id, :value=>@department.id, :type=>"number", :class => "form-control d-none", :autocomplete => "off", :style => "color: rgb(0,0,0);" %>
        </div>
        <div class="form-group text-center">
            <% if @departmentimage.id %>
                <label id="btn_file_upload" class="btn btn-primary" for="fileupload" style="font-family: Montserrat, sans-serif;font-weight: normal;background-color: rgb(255,120,0);margin: 15px;margin-right: 0;margin-left: 0;color: rgba(255,255,255,0.9); cursor:pointer;border-color:#fed136;"><%= form_button %></label>
            <% else %>
                <label id="btn_file_upload" class="btn btn-primary disabled" style="font-family: Montserrat, sans-serif;font-weight: normal;background-color: rgb(255,120,0);margin: 15px;margin-right: 0;margin-left: 0;margin-bottom: 0;color: rgba(255,255,255,0.9); cursor:pointer;border-color:#fed136;"><%= form_button %></label>
            <% end %>
            <%= f.submit form_button, :id=>"fileupload", :class=> "btn btn-primary d-none", :style=> "background-color: #ffa555;font-weight: normal;" %>
            <small id="form_success" class="form-text text-success" style="margin-top:0px; position: absolute; opacity: 0;"><%= form_success %></small>
        </div>
    <% end %>
</div>

<script>
    function readImage(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#preview_image').attr('src', e.target.result)
                $('#btn_file_upload').removeClass('disabled')
                $('#btn_file_upload').attr('for', 'fileupload')
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

WebFinalProyect/app/views/departments/_formvideo.html.erb
<div class="login-dark" style="background-image: url(<%= image_url 'backgrounds/form-bg.jpg' %>);">
    <%= form_with(model: @departmentvideo, html: {style: "background-color: rgba(255,255,255,0.9); max-width:350px;" }) do |f| %>
        <h2 class="text-center" style="color: #ffa555;font-size: 26px; margin-bottom:20px;color: rgb(255,120,0);">Agregar Vídeo</h2>
        <p class="form-control text-center" style="color: rgb(0,0,0); border-bottom: none; margin-top:-15px; font-size:20px;">Proyecto <%= @proyect.name %></p>
        <p class="form-control text-center" style="color: rgb(0,0,0); border-bottom: none; margin-top:-15px;font-size:15px;">Departamento <%= @department.number %></p>
        <div class="form-group">
            <small class="form-text text-secondary form-title">Nombre</small>
            <%= f.text_field :name, :value=>@departmentvideo.name, :type=>"text", :class => "form-control", :autocomplete => "off", :style => "color: rgb(0,0,0);" %>
            <p id="form_error_name_presence" class="form-text text-danger text-right form-error">Nombre obligatorio</p>
            <p id="form_error_name_uniqueness" class="form-text text-danger text-right form-error">Nombre ya existe</p>
        </div>
        <div class="form-group">
            <small class="form-text text-secondary form-title">URL Vídeo Youtube</small>
            <%= f.text_field :youtube_url, :value=>@departmentvideo.youtube_url, :type=>"text", :class => "form-control", :autocomplete => "off", :style => "color: rgb(0,0,0);" %>
            <p id="form_error_youtube_url_start_with" class="form-text text-danger text-right form-error">URL Vídeo Youtube No Válido</p>
            <p id="form_error_youtube_url_presence" class="form-text text-danger text-right form-error">URL Vídeo Youtube obligatorio</p>
            <p id="form_error_youtube_url_uniqueness" class="form-text text-danger text-right form-error">URL Vídeo Youtube ya existe</p>
        </div>
        <div class="form-group">
            <small class="form-text text-secondary form-title">Descripción</small>
            <%= f.text_area :description, :value=>@departmentvideo.description, :rows=>3, :class => "form-control", :autocomplete => "off", :style => "color: rgb(0,0,0);" %>
        </div>
        <div class="form-group">
            <%= f.text_field :department_id, :value=>@department.id, :type=>"number", :class => "form-control d-none", :autocomplete => "off", :style => "color: rgb(0,0,0);" %>
        </div>
        <div class="form-group text-center">
            <%= f.submit form_button, :class=> "btn btn-primary", :style=> "background-color: #ffa555;font-weight: normal;background-color: rgb(255,120,0);" %>
            <small id="form_success" class="form-text text-success" style="margin-top:0px; position: absolute; opacity: 0;"><%= form_success %></small>
        </div>
    <% end %>
</div>

WebFinalProyect/app/views/departments/edit.html.erb
<% @title="Información del Departamento" %><!---->
<% @navlist=[
    {:text=>"Departamentos",:controller=>"departments",:action=>"index"},
    {:text=>"Información",:controller=>"departments",:action=>"edit"},
    {:text=>"Imágenes",:controller=>"departments",:action=>"images"},
    {:text=>"Vídeos",:controller=>"departments",:action=>"videos"}
] %><!---->

<%= render "form", form_title: "Editar", form_button: "Guardar", form_success: "Cambios Guardados" %>

WebFinalProyect/app/views/departments/editimage.erb
<% @title="Editar Imagen del Departamento" %><!---->
<% @navlist=[
    {:text=>"Imágenes",:controller=>"departments",:action=>"images"}
] %><!---->

<%= render "formimage", form_title: "Editar", form_button: "Guardar", form_success: "Cambios Guardados", form_url: departmentimage_path %>

WebFinalProyect/app/views/departments/editvideo.erb
<% @title="Editar Vídeo" %><!---->
<% @navlist=[
    {:text=>"Vídeos",:controller=>"departments",:action=>"videos"}
] %><!---->

<%= render "formvideo", form_title: "Subir", form_button: "Subir", form_success: "Subida Exitosa", form_url: nil %>

WebFinalProyect/app/views/departments/index.html.erb
<% @title="Lista de Departamentos" %><!---->
<% @navlist=[
   {:text=>"Proyectos",:controller=>"proyects",:action=>"index"},
   {:text=>"Información",:controller=>"proyects",:action=>"edit"},
   {:text=>"Portada",:controller=>"proyects",:action=>"editcoverpage"},
   {:text=>"Departamentos",:controller=>"departments",:action=>"index"}
] %><!---->

<section id="portfolio" style="padding: 75px 0px;background-image: url(<%= image_url 'backgrounds/list-bg.jpg' %>);">
   <div class="container" style="margin-top: 90px;">
      <div class="row justify-content-center" style="margin-bottom: -15px;">
         <div class="login-dark" style="background-image: none;width: 95%;background-color: rgba(255,255,255,0.9);padding: 40px;border-radius: 4px;box-shadow: 3px 3px 4px rgba(0,0,0,0.2);height: auto;">
            <h2 class="text-center" style="color: #ffa555;font-size: 26px; margin-bottom:20px;color: rgb(255,120,0);">Listado de Departamentos</h2>
            <div class="row">
               <div class="col-6">
                  <%= link_to option={:controller=>"departments",:action=>"new"},html_options={:class=>"btn btn-primary",:role=>"button",:style=>"font-family: Montserrat, sans-serif;font-weight: normal;background-color: rgb(255,165,85);margin: 15px;margin-right: 0;margin-left: 0;color: rgba(255,255,255,0.9);background-color: rgb(255,120,0);"} do %>
                     Agregar Departamento
                  <% end %>
               </div>
               <div class="col text-left align-self-center align-middle">
                  <p class="text-right" style="color: rgb(0,0,0);border-bottom: none;margin-top: 15px;font-size: 24px;">Proyecto <%= @proyect.name %></p>
               </div>
            </div>
            <div class="table-responsive table-striped" style="border-radius: 10px;">
               <table class="table" style="margin:0px;">
                  <thead style="background-color: rgba(52,58,64,0.75);color: rgb(255,255,255);">
                     <tr>
                        <th class="align-middle">Número</th>
                        <th class="align-middle"><strong>Piso</strong><br></th>
                        <th class="align-middle"><strong>Área en m²</strong><br></th>
                        <th class="align-middle" style="text-align: center;"></th>
                        <th class="align-middle" style="text-align: center;"></th>
                     </tr>
                  </thead>
                  <tbody>
                     <% @departments.reverse_each do |department| %>
                        <tr>
                           <td class="align-middle"><%= department.number %></td>
                           <td class="align-middle"><%= department.floor %>º Piso</td>
                           <td class="align-middle"><%= number_with_delimiter(number_with_precision(department.area_m2, :precision => 2)) %> m²</td>
                           <td class="text-center">
                              <%= link_to option={:controller=>"departments",:action=>"edit", :department_id=>department}, html_options={:class=>"btn btn-outline-dark"} do %>
                                    <i class="fa fa-pencil"></i>
                              <% end %>
                           </td>
                           <td class="text-center">
                              <%= link_to option={:controller=>"departments",:action=>"destroy", :department_id=>department}, html_options={:class=>"btn btn-outline-danger", method: :delete, data: { confirm: '¿Estás Seguro?' }} do %>
                                    <i class="fa fa-remove"></i>
                              <% end %>
                           </td>
                        </tr>
                     <% end %>
                  </tbody>
               </table>
            </div>
         </div>
      </div>
   </div>
</section>

WebFinalProyect/app/views/departments/new.html.erb
<% @title="Registrar Departamento" %><!---->
<% @navlist=[
   {:text=>"Departamentos",:controller=>"departments",:action=>"index"}
] %><!---->

<%= render "form", form_title: "Registrar", form_button: "Registrar", form_success: "Registro Exitoso" %>